### ISSUE TITLE
Tests don't distinguish between ICE and expected compilation failure

### ISSUE THREAD

**Issue by mitaa** [steveklabnik/glacier#143]
`test.sh` currently checks for a non-null exit status code, but using the example of rust-lang/rust/issues/29191 and rust-lang/rust/issues/28971, which are now [fixed](https://github.com/rust-lang/rust/pull/29515), the ICEing and erroring exit code are the same.

**Comment by nodakai** [comment]
rust-lang/rust#20847 no longer crashes but we need to add `#[feature(fn_traits, ...`
